import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import LandingNavbar from "@/components/LandingNavbar";
import { Toaster } from "react-hot-toast";
import MainPage from "@/pages/MainPage";
import Footer from "@/components/Footer";

const inter = Poppins({ subsets: ["latin"],weight:['200','300','400','500','600','700','800','900'] });

export const metadata = {
  title: "Tomato Food Delivery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-8 md:px-16 lg:px-24 py-8`}>
      <MainPage>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
          <div className=" sticky bg-white z-50 top-0 left-0 w-full">
            <LandingNavbar />
          </div>
          {children}
          <Footer />
      </MainPage>
      </body>
    </html>
  );
}
